main:
  project_name: LSTM_CLASSIFIER
  experiment_name: dev
data:
  path1: "./model_trainning/ART_MED_1109.xlsx"
  path2: "./model_trainning/new_art.csv"
  path3: "./model_trainning/generated_result.csv"
model:
  maxlen: 40
  epoch: 400
  batch_size: 32
  model_name: "./model_trainning/letter_model.h5"
  embedding_weights: "./model_trainning/embedding_weights.npy"
  wandb_model: "letter_model.h5"
  word_dict_name: "./model_trainning/word_dicts2.json"
  wanbd_word_dict: "word_dicts2.json"
  output_dict: "./model_trainning/output_dicts2.json"
  wandb_output_dict: "output_dicts2.json"
retrain:
  threshold: 2
  current_count: 28
